export const CLEAR_RESULTS = 'CLEAR_RESULTS';
export const GET_NEXT_PAGE = 'GET_NEXT_PAGE';
export const REQUEST_SEARCH = 'REQUEST_SEARCH';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const UPDATE_OPTIONS = 'UPDATE_OPTIONS';
export const UPDATE_QUERY = 'UPDATE_QUERY';